export const FETCH_CHAIRS_REQUEST = "FETCH_CHAIRS_REQUEST";
export const FETCH_CHAIRS_SUCCESS = "FETCH_CHAIRS_SUCCESS";
export const FETCH_CHAIRS_FAILURE = "FETCH_CHAIRS_FAILURE";
export const FILTER_CHAIRS_BY_PRICE_LOW_TO_HIGH =
  "FILTER_CHAIRS_BY_PRICE_LOW_TO_HIGH";
export const FILTER_CHAIRS_BY_PRICE_HIGH_TO_LOW =
  "FILTER_CHAIRS_BY_PRICE_HIGH_TO_LOW";
export const FILTER_CHAIRS_BY_CATEGORY = "FILTER_CHAIRS_BY_CATEGORY";
export const ADD_TO_FAVORITES_REQUEST = "ADD_TO_FAVORITES_REQUEST";
