
export const FETCH_CHAIRS_REQUEST = "FETCH_CHAIRS_REQUEST";
export const FETCH_CHAIRS_SUCCESS = "FETCH_CHAIRS_SUCCESS";
export const FETCH_CHAIRS_FAILURE = "FETCH_CHAIRS_FAILURE";
export const FILTER_CHAIRS = "FILTER_CHAIRS";
export const SORT_CHAIRS = "SORT_CHAIRS";

