export const FETCH_CURTAINS_REQUEST = "FETCH_CURTAINS_REQUEST";
export const FETCH_CURTAINS_SUCCESS = "FETCH_CURTAINS_SUCCESS";
export const FETCH_CURTAINS_FAILURE = "FETCH_CURTAINS_FAILURE";
export const FILTER_CURTAINS = "FILTER_CURTAINS";
export const SORT_CURTAINS = "SORT_CURTAINS";
