
export const FETCH_SOFAS_REQUEST = "FETCH_SOFAS_REQUEST";
export const FETCH_SOFAS_SUCCESS = "FETCH_SOFAS_SUCCESS";
export const FETCH_SOFAS_FAILURE = "FETCH_SOFAS_FAILURE";
export const FILTER_SOFAS = "FILTER_SOFAS";
export const SORT_SOFAS = "SORT_SOFAS";
