
export const FETCH_TABLES_REQUEST = "FETCH_TABLES_REQUEST";
export const FETCH_TABLES_SUCCESS = "FETCH_TABLES_SUCCESS";
export const FETCH_TABLES_FAILURE = "FETCH_TABLES_FAILURE";
export const FILTER_TABLES = "FILTER_TABLES";
export const SORT_TABLES = "SORT_TABLES";

