// wardropeTypes.js

export const FETCH_WARDROBES_REQUEST = "FETCH_WARDROBES_REQUEST";
export const FETCH_WARDROBES_SUCCESS = "FETCH_WARDROBES_SUCCESS";
export const FETCH_WARDROBES_FAILURE = "FETCH_WARDROBES_FAILURE";
export const FILTER_WARDROBES = "FILTER_WARDROBES";
export const SORT_WARDROBES = "SORT_WARDROBES";
